add wsl checks

diff --git a/act3-login b/act3-login
--- a/act3-login
+++ b/act3-login
@@ -48,16 +48,16 @@ mkdir -p "$XDG_CACHE_HOME/act3/login" && touch "$LOG_FILE"
 echo -e "\nLogs: $LOG_FILE"
 
 # Log XDG directories
-echo "XDG_CACHE_HOME=$XDG_CACHE_HOME" > "$LOG_FILE"
-echo "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR" > "$LOG_FILE"
-echo "XDG_CONFIG_HOME=$XDG_CONFIG_HOME" > "$LOG_FILE"
+echo "XDG_CACHE_HOME=$XDG_CACHE_HOME" >> "$LOG_FILE"
+echo "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR" >> "$LOG_FILE"
+echo "XDG_CONFIG_HOME=$XDG_CONFIG_HOME" >> "$LOG_FILE"
 
 command -v brew >/dev/null 2>&1 || { echo -e "Homebrew not installed, install Homebrew with the following command:\n\n/bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\"\n\nAborting."; exit 1; }
 
 echo "Checking Homebrew installation..."
-brew doctor > "$LOG_FILE" 2>&1 || { echo -e "${yellow}WARNING: Detected issues with your Homebrew installation that could cause ACT3 Login to fail. Run \"brew doctor\" to check your system for potential problems.${normal}"; }
+brew doctor >> "$LOG_FILE" 2>&1 || { echo -e "${yellow}WARNING: Detected issues with your Homebrew installation that could cause ACT3 Login to fail. Run \"brew doctor\" to check your system for potential problems.${normal}"; }
 
-if [[ "$OSTYPE" == "linux-gnu" ]] && dpkg -s dev-tools > "$LOG_FILE" 2>&1; then
+if [[ "$OSTYPE" == "linux-gnu" ]] && dpkg -s dev-tools >> "$LOG_FILE" 2>&1; then
   echo "Detected an installation of the deprecated ACT3 dev-tools package. This will cause conflicts with installations of Homebrew ACE Tools."
   echo "Run \"apt remove dev-tools\""
 fi
@@ -65,10 +65,10 @@ fi
 # Update in case yq/jq/crane/docker-credential-helper are out of date
 echo -e "\nUpdating Homebrew Formula dependencies..."
 echo "Running brew update..."
-brew update > "$LOG_FILE" 2>&1 || echo "${yellow}Error: brew update failed, you may want to run \"brew doctor\" to check your Homebrew installation${normal}"
+brew update >> "$LOG_FILE" 2>&1 || echo "${yellow}Error: brew update failed, you may want to run \"brew doctor\" to check your Homebrew installation${normal}"
 echo "Running brew upgrade..."
 # all_dependencies="docker-credential-helper yq crane git-credential-libsecret direnv act3-pt kubectl"
-brew upgrade > "$LOG_FILE" 2>&1 || echo "${yellow}Error: brew upgrade failed, you may want to run \"brew doctor\" to check your Homebrew installation${normal}"
+brew upgrade >> "$LOG_FILE" 2>&1 || echo "${yellow}Error: brew upgrade failed, you may want to run \"brew doctor\" to check your Homebrew installation${normal}"
 
 # Read Personal Access Token
 # TODO: link to PAT docs? maybe from dubdubdub
@@ -86,44 +86,46 @@ echo -e "\n${bold}Setting up credentials for the ACT3 GitLab Container Registry$
 # Use yq to add credsStore field to ~/.docker/config.json
 # Use crane to log in to reg.git.act3-ace.com (crane checks login)
 echo -e "Checking for dependencies: docker-credential-helper, yq, crane"
-brew list docker-credential-helper > "$LOG_FILE" 2>&1 || { echo -e "\tInstalling docker-credential-helper"; brew install docker-credential-helper > "$LOG_FILE"; }
-brew list yq > "$LOG_FILE" 2>&1 || { echo -e "\tInstalling yq"; brew install yq > "$LOG_FILE"; }
-brew list crane > "$LOG_FILE" 2>&1 || { echo -e "\tInstalling crane"; brew install crane > "$LOG_FILE"; }
+brew list docker-credential-helper >> "$LOG_FILE" 2>&1 || { echo -e "\tInstalling docker-credential-helper"; brew install docker-credential-helper >> "$LOG_FILE"; }
+brew list yq >> "$LOG_FILE" 2>&1 || { echo -e "\tInstalling yq"; brew install yq >> "$LOG_FILE"; }
+brew list crane >> "$LOG_FILE" 2>&1 || { echo -e "\tInstalling crane"; brew install crane >> "$LOG_FILE"; }
 
 CREDS_STORE="secretservice"
 if [[ "$OSTYPE" == "darwin"* ]]; then
 	CREDS_STORE="osxkeychain"
 fi
 
-echo "Configuring registry authentication to use \"$CREDS_STORE\" ($HOME/.docker/config.json)"
-mkdir -p "$HOME/.docker"
-touch -a "$HOME/.docker/config.json" # -a tells touch to only change the "access" and "change" times
-"$BREW_BIN"/yq e -i -o=json ".credsStore = \"$CREDS_STORE\"" "$HOME/.docker/config.json"
-"$BREW_BIN"/yq e -i -o=json ".credHelpers.\"reg.git.act3-ace.com\" = \"$CREDS_STORE\"" "$HOME/.docker/config.json"
+if [[ -z "$WSL_DISTRO_NAME" ]]; then
+  echo "Configuring registry authentication to use \"$CREDS_STORE\" ($HOME/.docker/config.json)"
+  mkdir -p "$HOME/.docker"
+  touch -a "$HOME/.docker/config.json" # -a tells touch to only change the "access" and "change" times
+  "$BREW_BIN"/yq e -i -o=json ".credsStore = \"$CREDS_STORE\"" "$HOME/.docker/config.json"
+  "$BREW_BIN"/yq e -i -o=json ".credHelpers.\"reg.git.act3-ace.com\" = \"$CREDS_STORE\"" "$HOME/.docker/config.json"
+fi
 
 echo "Logging into the ACT3 GitLab Container Registry with Crane (reg.git.act3-ace.com)"
-printf '%s\n' "$TOKEN" | "$BREW_BIN"/crane auth login reg.git.act3-ace.com -u "$USERNAME" --password-stdin > "$LOG_FILE"
+printf '%s\n' "$TOKEN" | "$BREW_BIN"/crane auth login reg.git.act3-ace.com -u "$USERNAME" --password-stdin >> "$LOG_FILE"
 
 # GIT CREDENTIAL STORAGE SETUP
 echo -e "\n${bold}Setting up Git credentials for the ACT3 GitLab instance${normal}"
 
 # https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage
-if [[ "$OSTYPE" == "linux-gnu" ]]; then
+if [[ "$OSTYPE" == "linux-gnu" && -z "$WSL_DISTRO_NAME"]]; then
   echo "Checking for dependencies: git-credential-libsecret"
-	brew list git-credential-libsecret > "$LOG_FILE" 2>&1 || { echo -e "\tInstalling git-credential-libsecret"; brew install git-credential-libsecret > "$LOG_FILE"; }
+	brew list git-credential-libsecret >> "$LOG_FILE" 2>&1 || { echo -e "\tInstalling git-credential-libsecret"; brew install git-credential-libsecret >> "$LOG_FILE"; }
 
   echo "Configuring Git to use credential helper \"libsecret\""
-  git config --global credential.helper "libsecret" > "$LOG_FILE"
+  git config --global credential.helper "libsecret" >> "$LOG_FILE"
 
   echo "Storing credentials for the ACT3 GitLab Instance (git.act3-ace.com)"
-  printf 'protocol=https\nhost=git.act3-ace.com\nusername=%s\npassword=%s\n' "$USERNAME" "$TOKEN" | "$BREW_BIN"/git-credential-libsecret store > "$LOG_FILE"
+  printf 'protocol=https\nhost=git.act3-ace.com\nusername=%s\npassword=%s\n' "$USERNAME" "$TOKEN" | "$BREW_BIN"/git-credential-libsecret store >> "$LOG_FILE"
 elif [[ "$OSTYPE" == "darwin"* ]]; then
 	# I think MacOS comes with this pre-installed or it's part of git?
   echo "Configuring Git to use credential helper \"osxkeychain\""
-  git config --global credential.helper "osxkeychain" > "$LOG_FILE"
+  git config --global credential.helper "osxkeychain" >> "$LOG_FILE"
 
   echo "Storing credentials for the ACT3 GitLab Instance (git.act3-ace.com)"
-  printf 'protocol=https\nhost=git.act3-ace.com\nusername=%s\npassword=%s\n' "$USERNAME" "$TOKEN" | git credential-osxkeychain store > "$LOG_FILE"
+  printf 'protocol=https\nhost=git.act3-ace.com\nusername=%s\npassword=%s\n' "$USERNAME" "$TOKEN" | git credential-osxkeychain store >> "$LOG_FILE"
 
   [[ $(command -v git) == "/usr/bin/git" ]] || echo "${yellow}WARNING: Your system is using a non-standard installation of git. Use \"/usr/bin/git\" to take advantage of macOS keychain secure credential storage. If you have installed git via Homebrew, run \"brew uninstall git\"${normal}"
 fi
@@ -133,7 +135,7 @@ echo -e "\n${bold}NETRC Creation (for Golang development)${normal}"
 
 create_netrc () {
 echo "Checking for dependencies: direnv"
-brew list direnv > "$LOG_FILE" 2>&1 || { echo -e "\tInstalling direnv"; brew install direnv > "$LOG_FILE"; }
+brew list direnv >> "$LOG_FILE" 2>&1 || { echo -e "\tInstalling direnv"; brew install direnv >> "$LOG_FILE"; }
 
 mkdir -p "$XDG_CONFIG_HOME/direnv"
 touch -a "$XDG_CONFIG_HOME/direnv/direnvrc"
@@ -165,22 +167,24 @@ echo -e "\n${bold}Setting up the ACE Tools Homebrew Tap${normal}"
 
 # Tap act3/ace-tools if not already tapped
 echo "Checking for the act3/ace-tools Homebrew Tap... "
-[[ $(brew tap) =~ "act3/ace-tools" ]] || { echo -e "Adding the act3/ace-tools Homebrew Tap"; brew tap act3/ace-tools https://git.act3-ace.com/ace/homebrew-ace-tools.git > "$LOG_FILE"; }
+[[ $(brew tap) =~ "act3/ace-tools" ]] || { echo -e "Adding the act3/ace-tools Homebrew Tap"; brew tap act3/ace-tools https://git.act3-ace.com/ace/homebrew-ace-tools.git >> "$LOG_FILE"; }
 echo -e "act3/ace-tools tap added, check available formulas with \"brew search act3/ace-tools\""
 
 echo "Upgrading Homebrew Formulae"
-brew update > "$LOG_FILE" 2>&1 || echo "${yellow}Error: brew update failed, you may want to run \"brew doctor\" to check your Homebrew installation${normal}"
-brew upgrade > "$LOG_FILE" 2>&1 || echo "${yellow}Error: brew upgrade failed, you may want to run \"brew doctor\" to check your Homebrew installation${normal}"
+brew update >> "$LOG_FILE" 2>&1 || echo "${yellow}Error: brew update failed, you may want to run \"brew doctor\" to check your Homebrew installation${normal}"
+brew upgrade >> "$LOG_FILE" 2>&1 || echo "${yellow}Error: brew upgrade failed, you may want to run \"brew doctor\" to check your Homebrew installation${normal}"
 
 # GITLAB API CREDENTIALS FOR PROJECT TOOL
-echo -e "\n${bold}Setting up GitLab API Credentials for ACT3 Project Tool (act3-pt)${normal}"
+if [[ -z "$WSL_DISTRO_NAME" ]]; then
+  echo -e "\n${bold}Setting up GitLab API Credentials for ACT3 Project Tool (act3-pt)${normal}"
 
-# Install act3-pt and log in to git.act3-ace.com
-echo "Checking for act3-pt... "
-brew list act3-pt > "$LOG_FILE" 2>&1 || { echo -e "\tInstalling act3-pt"; brew install act3-pt > "$LOG_FILE"; }
+  # Install act3-pt and log in to git.act3-ace.com
+  echo "Checking for act3-pt... "
+  brew list act3-pt >> "$LOG_FILE" 2>&1 || { echo -e "\tInstalling act3-pt"; brew install act3-pt >> "$LOG_FILE"; }
 
-echo "Logging in with act3-pt"
-printf '%s\n' "$TOKEN" | "$BREW_BIN"/act3-pt login --name act3 --url git.act3-ace.com --token-stdin > "$LOG_FILE"
+  echo "Logging in with act3-pt"
+  printf '%s\n' "$TOKEN" | "$BREW_BIN"/act3-pt login --name act3 --url git.act3-ace.com --token-stdin >> "$LOG_FILE"
+fi
 
 # TELEMETRY SERVER SETUP FOR ACE-DT
 echo -e "\n${bold}Setting up Telemetry Server for ACE Data Tool (ace-dt)${normal}"
@@ -263,9 +267,9 @@ echo "You must import this user configuration file to ACE Hub to use your creden
 echo -e "\n${bold}Setting up ACT3 Kubernetes cluster access${normal}"
 
 echo -e "Checking for dependencies: kubectl, krew, oidc-login"
-brew list kubernetes-cli > "$LOG_FILE" 2>&1 || { echo -e "\tInstalling kubectl"; brew install kubernetes-cli > "$LOG_FILE"; }
-brew list krew > "$LOG_FILE" 2>&1 || { echo -e "\tInstalling krew"; brew install krew > "$LOG_FILE"; }
-command -v kubectl-oidc-login >/dev/null 2>&1 || { echo -e "\tInstalling konfig"; "$BREW_BIN"/kubectl-krew install oidc-login > "$LOG_FILE"; }
+brew list kubernetes-cli >> "$LOG_FILE" 2>&1 || { echo -e "\tInstalling kubectl"; brew install kubernetes-cli >> "$LOG_FILE"; }
+brew list krew >> "$LOG_FILE" 2>&1 || { echo -e "\tInstalling krew"; brew install krew >> "$LOG_FILE"; }
+command -v kubectl-oidc-login >/dev/null 2>&1 || { echo -e "\tInstalling konfig"; "$BREW_BIN"/kubectl-krew install oidc-login >> "$LOG_FILE"; }
 
 # curl the file from wherever it ends up 
 CLUSTERCONFIG="$HOME/.kube/act3.yaml"
@@ -323,7 +327,6 @@ EOF
 echo "Backing up existing configuration to \"$HOME/.kube/config.bak\""
 [ -f "$HOME/.kube/config" ] && cp "$HOME/.kube/config" "$HOME/.kube/config.bak-$(date +%s)"
 echo "Merging cluster configuration into \"$HOME/.kube/config\"."
-# "$BREW_BIN"/kubectl konfig import --save "$CLUSTERCONFIG"
 KUBECONFIG=~/.kube/config:"$CLUSTERCONFIG" "$BREW_BIN"/kubectl config view --raw > ~/.kube/config.new && cp ~/.kube/config.new ~/.kube/config
 
 echo "Creating secret in namespace $USERNAME-workspace"
